version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file shared-template.yaml --s3-bucket osi-saas-server-tenant-mgmt --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml